/**
 * users-admin-guard.e2e-spec.ts
 *
 * WHY THIS SPEC EXISTS
 * --------------------
 * The unit tests in users.service.spec.ts and scenarios.service.spec.ts mock
 * the TypeORM QueryBuilder and getCount. That means:
 *
 *   - The SQL generated by countOtherActiveAdmins (which previously combined
 *     FOR UPDATE + COUNT) is NEVER sent to a real DB — the mocked getCount()
 *     just resolves a number, so the illegal SQL goes undetected.
 *   - The .set({ updated_at: ... }) property-name mismatch in transferOwnership
 *     is NEVER checked by TypeORM's metadata resolver — the mocked execute()
 *     just resolves, so EntityPropertyNotFoundError never fires.
 *
 * Only a real PostgreSQL connection exercises both paths. This spec runs
 * against the test DB (port 5433, via setup-e2e.ts) with migrationsRun: true,
 * meaning the seed admin (basualdofelipe@gmail.com) is always present.
 *
 * REQUIREMENT: docker compose up -d postgres-test (postgres-test on port 5433)
 * must be running before executing this suite. Run with:
 *   npm run test:e2e -- --testPathPattern=users-admin-guard
 * or:
 *   npx jest --config ./test/jest-e2e.json test/users-admin-guard.e2e-spec.ts --runInBand
 *
 * TESTS
 * -----
 * 1. last-admin guard does NOT crash (BLOCKER 1): demoting a non-last admin
 *    exercises countOtherActiveAdmins with real SQL. Pre-fix → FOR UPDATE +
 *    aggregate error; post-fix → resolves OK.
 *
 * 2. last-admin guard returns 400 (not 500): the precondition "exactly 1 active
 *    admin" is built by reconciling against the seed admin (never assuming an
 *    empty table). Pre-fix → 500 QueryFailedError; post-fix → BadRequestException.
 *
 * 3. delete with scenario transfer does NOT crash (BLOCKER 2): calls
 *    usersService.remove() on a user who owns a Scenario, verifying that the
 *    user is deleted and the scenario is transferred + renamed + updatedAt bumped.
 *    Pre-fix → EntityPropertyNotFoundError (updated_at property not found);
 *    post-fix → resolves OK.
 */

import { BadRequestException, INestApplication } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import { DataSource, Repository } from 'typeorm';
import { AppModule } from '../src/app.module';
import { UsersService } from '../src/users/users.service';
import { User } from '../src/users/entities/user.entity';
import { Role } from '../src/roles/entities/role.entity';
import { Scenario } from '../src/scenarios/entities/scenario.entity';

// Unique prefix for all test-created rows — makes cleanup safe and targeted.
const TEST_PREFIX = 'e2e-admin-guard-';

describe('UsersService admin-guard integration (real Postgres)', () => {
  let app: INestApplication;
  let moduleFixture: TestingModule;
  let dataSource: DataSource;
  let usersService: UsersService;

  let userRepo: Repository<User>;
  let roleRepo: Repository<Role>;
  let scenarioRepo: Repository<Scenario>;

  // Roles resolved from the seeded DB (not created by tests)
  let adminRole: Role;
  let editorRole: Role;

  // The seed admin is always present after migrationsRun: true.
  // We NEVER hard-delete it — only deactivate temporarily in a transaction
  // when a test needs to isolate "exactly 1 active admin".
  const SEED_ADMIN_EMAIL = 'basualdofelipe@gmail.com';

  beforeAll(async () => {
    moduleFixture = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();

    dataSource = moduleFixture.get(DataSource);
    usersService = moduleFixture.get(UsersService);

    userRepo = dataSource.getRepository(User);
    roleRepo = dataSource.getRepository(Role);
    scenarioRepo = dataSource.getRepository(Scenario);

    // Resolve roles by permission flags (seeded by migrations).
    // admin role = canManageUsers: true; editor role = canManageUsers: false.
    adminRole = await roleRepo.findOneOrFail({
      where: { canManageUsers: true, isSystem: true },
    });
    editorRole = await roleRepo.findOneOrFail({
      where: { canManageUsers: false, isSystem: true },
    });
  });

  afterAll(async () => {
    await app.close();
  });

  /**
   * WR-04: defensively reactivate the seed admin before every test so the
   * suite self-heals against a predecessor run that crashed between Test 2's
   * deactivation and its afterEach restore. Without this, a long-lived shared
   * test DB could start a run with the real admin deactivated.
   */
  beforeEach(async () => {
    await dataSource.query(
      `UPDATE users SET is_active = true WHERE email = $1`,
      [SEED_ADMIN_EMAIL],
    );
  });

  /**
   * Delete all test-prefixed rows after each test to isolate runs.
   * Order: scenarios → users (FK: scenarios.user_id → users.id).
   * The seed admin (basualdofelipe@gmail.com) is never deleted here.
   */
  afterEach(async () => {
    // Delete test scenarios (identified by the test prefix in the name)
    await dataSource.query(`DELETE FROM scenarios WHERE name LIKE $1`, [
      `${TEST_PREFIX}%`,
    ]);
    // Delete test users (identified by the email prefix)
    await dataSource.query(`DELETE FROM users WHERE email LIKE $1`, [
      `${TEST_PREFIX}%`,
    ]);
    // Restore seed admin to active (in case a test deactivated it)
    await dataSource.query(
      `UPDATE users SET is_active = true WHERE email = $1`,
      [SEED_ADMIN_EMAIL],
    );
  });

  // ─── Helper: insert a test user with a given role ──────────────
  async function createTestUser(
    suffix: string,
    role: Role,
    isActive = true,
  ): Promise<User> {
    const user = userRepo.create({
      email: `${TEST_PREFIX}${suffix}@test.com`,
      name: `Test User ${suffix}`,
      role,
      isActive,
    });
    return userRepo.save(user);
  }

  // ─── Helper: insert a test scenario owned by a user ───────────
  async function createTestScenario(
    owner: User,
    nameSuffix: string,
  ): Promise<Scenario> {
    const scenario = scenarioRepo.create({
      name: `${TEST_PREFIX}${nameSuffix}`,
      user: owner,
      isPublic: false,
    });
    return scenarioRepo.save(scenario);
  }

  // ─────────────────────────────────────────────────────────────────
  // Test 1: Demoting a non-last admin does NOT crash (BLOCKER 1)
  // ─────────────────────────────────────────────────────────────────
  it('Test 1 (BLOCKER 1): demoting a non-last admin resolves OK without SQL error', async () => {
    // With the seed admin active (canManageUsers=true, isActive=true) + a
    // second test admin, there are >=2 active admins. Demoting the test admin
    // to editor calls countOtherActiveAdmins with real SQL.
    // Pre-fix: FOR UPDATE + COUNT → QueryFailedError 500
    // Post-fix: plain COUNT → resolves to 1+ → no BadRequestException
    const secondAdmin = await createTestUser('admin2', adminRole, true);
    // Demote the test admin (victim) with the seed admin as caller; both are
    // active so the last-admin guard must NOT fire — this exercises
    // countOtherActiveAdmins against real SQL.
    const seedAdmin = await userRepo.findOneOrFail({
      where: { email: SEED_ADMIN_EMAIL },
    });

    // Demote secondAdmin to editor (caller = seedAdmin.id)
    // This goes through countOtherActiveAdmins with real SQL.
    await expect(
      usersService.update(
        secondAdmin.id,
        { roleId: editorRole.id },
        seedAdmin.id,
      ),
    ).resolves.not.toThrow();
  }, 30000);

  // ─────────────────────────────────────────────────────────────────
  // Test 2: last-admin guard returns 400 (correct reconciliation with seed)
  // ─────────────────────────────────────────────────────────────────
  it('Test 2 (BLOCKER 1): last-admin guard rejects with BadRequestException (not 500) when deactivating the real last active admin', async () => {
    // BASELINE: the seed admin (basualdofelipe@gmail.com) is always active.
    // We need "exactly 1 active admin" for the guard to fire. Strategy:
    // temporarily deactivate the seed admin so that a freshly created test
    // admin becomes the sole active admin, then try to deactivate that test
    // admin and expect BadRequestException.
    //
    // The seed admin is NEVER hard-deleted — only SET is_active = false for
    // the duration of this test. afterEach restores it to true.
    await dataSource.query(
      `UPDATE users SET is_active = false WHERE email = $1`,
      [SEED_ADMIN_EMAIL],
    );

    // Count active admins now to confirm the baseline is 0 (besides the one
    // we are about to create)
    const [countRow] = await dataSource.query<[{ cnt: string }]>(
      `SELECT COUNT(*)::text AS cnt FROM users u
         JOIN roles r ON r.id = u.role_id
         WHERE u.is_active = true AND r.can_manage_users = true`,
    );
    const baselineCount = parseInt(countRow.cnt, 10);
    // After deactivating the seed admin, baseline should be 0 test admins
    expect(baselineCount).toBe(0);

    // Create the sole active admin
    const lastAdmin = await createTestUser('lastadmin', adminRole, true);

    // Use a separate editor as caller (can't be the same user as victim —
    // self-deactivate guard fires first and returns a different 400).
    const callerEditor = await createTestUser(
      'caller-editor',
      editorRole,
      true,
    );

    // Deactivating the last active admin must throw BadRequestException,
    // not QueryFailedError (the pre-fix behavior was a 500 SQL crash).
    await expect(
      usersService.update(lastAdmin.id, { isActive: false }, callerEditor.id),
    ).rejects.toThrow(BadRequestException);

    // Extra assertion: the message must be the last-admin guard, not the SQL error
    await expect(
      usersService.update(lastAdmin.id, { isActive: false }, callerEditor.id),
    ).rejects.toThrow(
      'No se puede dejar el sistema sin administradores activos',
    );
  }, 30000);

  // ─────────────────────────────────────────────────────────────────
  // Test 3: delete with scenario transfer does NOT crash (BLOCKER 2)
  // ─────────────────────────────────────────────────────────────────
  it('Test 3 (BLOCKER 2): delete user with scenarios resolves OK, scenario is transferred + renamed + updatedAt bumped', async () => {
    const seedAdmin = await userRepo.findOneOrFail({
      where: { email: SEED_ADMIN_EMAIL },
    });

    // Create a victim (non-admin, not self) who owns a scenario
    const victim = await createTestUser('victim', editorRole, true);
    const scenarioBefore = await createTestScenario(
      victim,
      'scenario-to-transfer',
    );
    const originalUpdatedAt = scenarioBefore.updatedAt;

    // Small delay to ensure NOW() will differ from createdAt
    await new Promise<void>((resolve) => setTimeout(resolve, 10));

    // Delete victim (caller = seed admin, different from victim)
    // Pre-fix: EntityPropertyNotFoundError on 'updated_at' → 500
    // Post-fix: resolves OK
    await expect(
      usersService.remove(victim.id, seedAdmin.id),
    ).resolves.toBeUndefined();

    // (a) victim user no longer exists
    const deletedUser = await userRepo.findOne({
      where: { id: victim.id },
    });
    expect(deletedUser).toBeNull();

    // (b) scenario now belongs to the caller (seedAdmin)
    const transferred = await scenarioRepo.findOne({
      where: { id: scenarioBefore.id },
      relations: ['user'],
    });
    expect(transferred).not.toBeNull();
    expect(transferred!.user.id).toBe(seedAdmin.id);

    // (c) scenario name contains the suffix pattern ' - <name> #<shortId>'
    const suffix = `Test User victim #${victim.id.slice(0, 8)}`;
    expect(transferred!.name).toContain(suffix);

    // (d) updatedAt was bumped by the bulk UPDATE's NOW()
    // The new updatedAt must be >= the original (and ideally > it, though
    // clock resolution may make them equal in extremely fast environments).
    expect(transferred!.updatedAt.getTime()).toBeGreaterThanOrEqual(
      originalUpdatedAt.getTime(),
    );
  }, 30000);
});
